services:
  - type: web
    name: trpc-starter-app
    env: node
    plan: free
    buildCommand: yarn --prod=false &&
      yarn build
    startCommand: yarn start
    healthCheckPath: /api/trpc/healthz
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        fromDatabase:
          name: trpc-starter-db
          property: connectionString

      - fromGroup: trpc-starter-env

databases:
  - name: trpc-starter-db
    plan: free
