root: true
parser: '@typescript-eslint/parser'

parserOptions: 
  project: tsconfig.json

extends: 
  - plugin:@typescript-eslint/recommended
  - airbnb-base
  - airbnb-typescript/base
  - prettier

plugins: 
  - '@typescript-eslint/eslint-plugin'
  - import
