name: Diagnostics

on:
  pull_request:
  push:
    branches:
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diagnostics:
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      fail-fast: false
      matrix:
        branch: ['main', 'next']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install --child-concurrency 3
      - run: pnpm build
      - run: mkdir diagnostics-results
      - run: cd ./examples/.diagnostics/big-router-declaration && pnpm tsc --extendedDiagnostics > ../diagnostics-results/diagnostics-${{ matrix.branch }}.txt

      - name: Upload diagnostics results
        uses: actions/upload-artifact@v2
        with:
          name: diagnostics-results
          path: ./diagnostics-results

  comment:
    needs: diagnostics
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all diagnostics results
        uses: actions/download-artifact@v2
        with:
          name: diagnostics-results

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm install -g ts-node typescript
      - run: tsx ../scripts/compareDiagnostics.ts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
