name: Examples E2E (old nodes)
on: [push]
jobs:
  e2e-old-nodes:
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/playwright
      # DATABASE_URL: postgresql://postgres:@postgres:5432/trpcdb
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        dir: [.interop/next-prisma-starter]
        # start example with:
        node-start: ['14.x']
        os: [ubuntu-latest]
    # services:
    #   postgres:
    #     image: postgres:12.1
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_DB: trpcdb
    #     ports:
    #       - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ matrix.dir }}-

      - run: node -v
      - name: Install deps and build (with cache)
        run: pnpm --filter ./examples/${{ matrix.dir }}  --filter "@trpc/*" --filter root install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ matrix.dir }}/.next/cache
          key: ${{ matrix.dir }}-${{ runner.os }}-${{ matrix.node-start }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-start }}

      - run: node -v

      # - name: Wait for postgres
      #   run: |
      #     until pg_isready -h postgres -p 5432 -U postgres; do
      #       sleep 1
      #     done

      # We currently don't have any examples that has `lint`, except for Next.js ones and they are linted at build
      # - name: if exists, run lint
      #   run: pnpm --filter ./examples/${{ matrix.dir }} --if-present lint

      # - name: Wait for postgres
      #   run: sleep 100

      - name: if exists, run build
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present build
      - name: if exists, run test-start
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-start
      - name: if exists, run test-dev
        run: pnpm --filter ./examples/${{ matrix.dir }} --if-present test-dev
