name: Examples
on: [push]
jobs:
  next-hello-world:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: microsoft/playwright-github-action@v1

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install & build
        run: |
          yarn --frozen-lockfile

      # - run: yarn --cwd examples/next-hello-world test-dev
      - run: yarn --cwd examples/next-hello-world build
      - run: yarn --cwd examples/next-hello-world test-start

  next-ssg-chat:
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: chat
        ports:
          # will assign a random free host port
          - 5432:5432
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: microsoft/playwright-github-action@v1

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Install & build
        run: |
          yarn --frozen-lockfile
      - run: yarn add playwright --dev
      # - run: yarn --cwd examples/next-ssg-chat test-dev
      - run: yarn --cwd examples/next-ssg-chat build
      - run: yarn --cwd examples/next-ssg-chat test-start
