name: Build & Test
on: [push]
jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ runner.os }}-build-${{ github.sha }}
      
      - run: yarn test --ci --coverage --maxWorkers=2

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./packages
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn lint
      - run: yarn manypkg check
