name: PR naming convention
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types:
      - edited

jobs:
  test:
    # Job name is Greeting
    name: PR naming convention
    # This job runs on Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '/^(chore|docs|(feat|fix|chore)\(`[^`]*`\)): /' # Regex the title should match.
          allowed_prefixes: 'feat,fix,chore' # title should start with the given prefix
          prefix_case_sensitive: true # title prefix are case insensitive
          min_length: 5 # Min length of the title
          github_token: ${{ github.token }} # Default: ${{ github.token }}
