# Originally inspired by Cloudflare Wrangler
# https://github.com/cloudflare/wrangler2/blob/main/.github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    # Don't trigger this on forks
    if: ${{ github.repository_owner == 'trpc' }}
    name: Create a release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Create Version PR # <-- this only happens when there are changesets registered
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_ENV: 'production'
