name: Release "@canary"-tagged packages

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/**'
      - '!packages/**/package.json'
      - '!packages/test/**'

jobs:
  publish:
    timeout-minutes: 10
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    runs-on: ubuntu-latest
    if: github.repository == 'trpc/trpc'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node and pnpm
        uses: ./.github/setup

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish canary version 
        run: pnpm lerna publish --force-publish --canary --preid canary --dist-tag canary --yes
